/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-05-31 10:20:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper {\r\n");
      out.write("\twidth: 275px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#col1 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#col2 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#col3 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#col4 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indexid {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 35%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inid {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 65%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indexpwd {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 35%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inpwd {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 65%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#textid {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#textpwd {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("#joinmember{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 35%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#funclist{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 65%;\r\n");
      out.write("}\r\n");
      out.write("#funclist button{\r\n");
      out.write("  width: 20%;\r\n");
      out.write("  border: 0px;\r\n");
      out.write("}\r\n");
      out.write("div button {\r\n");
      out.write("\tborder-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
 if(session.getAttribute("loginId")!=null){ 
      out.write("\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("    <div id=\"joinmember\">\r\n");
      out.write("       ");
      out.print(session.getAttribute("loginId")+ "님 환영합니다." );
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"funclist\">\r\n");
      out.write("      <button type=\"button\" id=\"logout\">로그아웃</button>\r\n");
      out.write("      <button type=\"button\" id=\"mypage\">나의페이지</button>\r\n");
      out.write("      <button type=\"button\" id=\"memberout\">회원탈퇴</button>\r\n");
      out.write("      <button type=\"button\" id=\"modify\">정보수정</button>\r\n");
      out.write("        <button type=\"button\" id=\"borad\">보드</button>\r\n");
      out.write("    </div>\r\n");
      out.write("        <button id=\"admin\" type=\"button\">회원관리</button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script>\r\n");
      out.write("  \t\tdocument.getElementById(\"logout\").onclick = function(){\r\n");
      out.write("        location.href=\"logout.jsp\";\r\n");
      out.write("      }\r\n");
      out.write("      document.getElementById(\"mypage\").onclick = function(){\r\n");
      out.write("        location.href=\"info.jsp\";\r\n");
      out.write("      }\r\n");
      out.write("      document.getElementById(\"memberout\").onclick = function(){\r\n");
      out.write("        location.href=\"out.jsp\";\r\n");
      out.write("      }\r\n");
      out.write("      document.getElementById(\"modify\").onclick = function(){\r\n");
      out.write("        location.href=\"modify.jsp\";\r\n");
      out.write("      }\r\n");
      out.write("      document.getElementById(\"borad\").onclick = function(){\r\n");
      out.write("          location.href=\"BorderList.jsp?currentPage\";\r\n");
      out.write("        }\r\n");
      out.write("      document.getElementById(\"admin\").onclick = function(){\r\n");
      out.write("\t\t\tlocation.href=\"admin/admin.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\t");

  }else{
	  
      out.write("\r\n");
      out.write("\t<form method=\"post\" action=\"loginchk.jsp\" id=\"logininfo\">\r\n");
      out.write("\t\t<div id=\"wrapper\">\r\n");
      out.write("\t\t\t<div id=\"col1\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t회원로그인\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"col2\">\r\n");
      out.write("\t\t\t\t<div id=\"indexid\">아이디:</div>\r\n");
      out.write("\t\t\t\t<div id=\"inid\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"textid\" name=\"id\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"col3\">\r\n");
      out.write("\t\t\t\t<div id=\"indexpwd\">비밀번호 :</div>\r\n");
      out.write("\t\t\t\t<div id=\"inpwd\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"textpwd\" name=\"pw\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"col4\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t<button id=\"log\" type=\"button\">로그인</button>\r\n");
      out.write("\t\t\t\t<button id=\"sign\" type=\"button\" >회원가입</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("        document.getElementById(\"sign\").onclick = function(){\r\n");
      out.write("            location.href=\"join.html\";\r\n");
      out.write("        }\r\n");
      out.write("        document.getElementById(\"log\").onclick = function(){\r\n");
      out.write("            document.getElementById(\"logininfo\").submit();\r\n");
      out.write("        }\r\n");
      out.write("\t\t\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\t");

  }


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
