/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-05-30 00:59:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import bean.MemberInfos;
import bean.DAO;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("bean.MemberInfos");
    _jspx_imports_classes.add("bean.DAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper {\r\n");
      out.write("\twidth: 275px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#col1 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#col2 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#col3 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#col4 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 25%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indexid {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 35%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inid {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 65%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#indexpwd {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 35%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#inpwd {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 65%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#textid {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#textpwd {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("#joinmember{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 35%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#funclist{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 65%;\r\n");
      out.write("}\r\n");
      out.write("#funclist button{\r\n");
      out.write("  width: 25%;\r\n");
      out.write("  border: 0px;\r\n");
      out.write("}\r\n");
      out.write("div button {\r\n");
      out.write("\tborder-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  \t");

  	  String var1 = (String)session.getAttribute("loginId");
      if( var1.equals("admin")){

     DAO data = new DAO();
     MemberInfos mif = new MemberInfos();
     List<MemberInfos> list = data.listAll();
     int listsize = list.size();
    
      out.write("\r\n");
      out.write("  \t<table border=1>\r\n");
      out.write("  \t<tr><th>회원관리</th></tr>\r\n");
      out.write("  \t<tr>\r\n");
      out.write("  \t<td>아이디</td>\r\n");
      out.write("  \t<td>이름</td>\r\n");
      out.write("  \t<td>번호</td>\r\n");
      out.write("  \t<td>이메일</td>\r\n");
      out.write("  \t<td>차단여부</td>\r\n");
      out.write("  \t</tr>\r\n");
      out.write("  \t");
 for(int i=0;i<listsize;i++) {
      out.write("\r\n");
      out.write("  \t<tr>\r\n");
      out.write("  \t<td>");
      out.print(list.get(i).getId());
      out.write("</td>\r\n");
      out.write("  \t<td>");
      out.print(list.get(i).getName());
      out.write("</td>\r\n");
      out.write("  \t<td>");
      out.print(list.get(i).getPhone1());
      out.write('-');
      out.print(list.get(i).getPhone2());
      out.write('-');
      out.print(list.get(i).getPhone3());
      out.write("</td>\r\n");
      out.write("  \t<td>");
      out.print(list.get(i).getEmail());
      out.write("</td>\r\n");
      out.write("  \t");
 if(list.get(i).getIsblocked().equals("n")) {
      out.write("\r\n");
      out.write("  \t <td align=\"center\"> <button id=\"block");
      out.print(i+1);
      out.write("\" type=\"button\">차단</button></td>\r\n");
      out.write("  \t");
} else {
      out.write("\r\n");
      out.write("  \t <td align=\"center\"> <button id=\"block");
      out.print(i+1);
      out.write("\" type=\"button\">해제</button></td>\r\n");
      out.write("  \t");
}
      out.write("\r\n");
      out.write("     <script>\r\n");
      out.write("       \r\n");
      out.write("  \t    document.getElementById(\"block\"+'");
      out.print(i+1);
      out.write("').onclick = function(){\r\n");
      out.write("        \t var text =  document.getElementById(\"block\"+'");
      out.print(i+1);
      out.write("').innerHTML;\r\n");
      out.write("  \t    \tif(text == '차단'){\r\n");
      out.write("  \t    \t\t document.getElementById(\"block\"+'");
      out.print(i+1);
      out.write("').innerHTML = \"해제\";\r\n");
      out.write("  \t            ");
int result = data.doblock(list.get(i).getId());
  	          System.out.print(list.get(i).getId());
  	               if(result>0){
  	            	   
      out.write(" alert(\"차단성공\");");

  	               }
  	            
      out.write("\r\n");
      out.write("  \t           \r\n");
      out.write("  \t    \t}else{\r\n");
      out.write("  \t    \t\t document.getElementById(\"block\"+'");
      out.print(i+1);
      out.write("').innerHTML = \"차단\";\r\n");
      out.write("   \t            ");
 int result2 = data.unblock(list.get(i).getId());
   	             System.out.print(list.get(i).getId());
   	            if(result2>0){
            	   
      out.write(" alert(\"차단해제\");");

               }
   	            
      out.write("\r\n");
      out.write("   \t            \r\n");
      out.write("  \t    \t}\r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("     </script>\r\n");
      out.write("     </tr>\r\n");
      out.write("\r\n");
      out.write("  \t");
 }
      out.write("\r\n");
      out.write("  \t</table>\r\n");
      out.write("\r\n");
      out.write("  \t");
}else{
  		response.sendRedirect("never.jsp");
  	
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"loginchk.jsp\" id=\"logininfo\">\r\n");
      out.write("      <div id=\"wrapper\">\r\n");
      out.write("        <div id=\"col1\" style=\"text-align: center\">\r\n");
      out.write("           권환이 없습니다\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"col2\">\r\n");
      out.write("        response.sendRedirect(\"error.jsp\");\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"col3\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"col4\" style=\"text-align: center\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
