/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-06-04 11:31:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.borde;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.FileInfos;
import bean.FileDao;
import bean.ReplyInfo;
import bean.ReplyDAO;
import bean.BorderInfos;
import java.util.List;
import bean.BoradDAO;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("bean.FileDao");
    _jspx_imports_classes.add("bean.BorderInfos");
    _jspx_imports_classes.add("bean.BoradDAO");
    _jspx_imports_classes.add("bean.ReplyInfo");
    _jspx_imports_classes.add("bean.ReplyDAO");
    _jspx_imports_classes.add("bean.FileInfos");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		int num = Integer.parseInt(request.getParameter("list.get(i).getSeq()"));
		String isid = (String) session.getAttribute("loginId");
		BoradDAO bdao = new BoradDAO();
		String hadid = bdao.ischk(num);
		if (isid.equals(hadid)) {
		} else {
			bdao.updateVisite(num);
		}
		List<BorderInfos> list = bdao.showGetPage(num);
		String iswriter = list.get(0).getWriter();

		if (iswriter.equals((String) session.getAttribute("loginId"))) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th colspan=\"5\" width=\"400\">");
      out.print(list.get(0).getTitle());
      out.write("</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.print(list.get(0).getIp());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.print(list.get(0).getWriter());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"1\">");
      out.print(list.get(0).getViewcount());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr height=\"400\">\r\n");
      out.write("\t\t\t<td colspan=\"5\">");
      out.print(list.get(0).getContents());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			ReplyDAO rdao = new ReplyDAO();
				List<ReplyInfo> listre = rdao.showReply(num);

				for (int i = 0; i < listre.size(); i++) {
					if (!(isid.equals(listre.get(i).getWriter()))) {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(listre.get(i).getWriter());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.print(listre.get(i).getComment_text());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(listre.get(i).getIp());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>작성날짜 ");
      out.print(listre.get(i).getWriterdate());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(listre.get(i).getWriter());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.print(listre.get(i).getComment_text());
      out.write("</td>\r\n");
      out.write("\t\t\t<td><button id=\"redel\">삭제</button> <button id=\"remod\">수정</button></td>\r\n");
      out.write("\t\t\t<td>작성날짜 ");
      out.print(listre.get(i).getWriterdate());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t <script>\r\n");
      out.write("            document.getElementById(\"redel\").onclick = function(){\r\n");
      out.write("            \tvar del = confirm(\"삭제하시겠습니까?\")\r\n");
      out.write("          \t  if(del == true){\r\n");
      out.write("          \t\t  location.href=\"deleteReply.jsp?lister.get=");
      out.print(listre.get(i).getComment_seq());
      out.write("&one=");
      out.print(num);
      out.write("\";\r\n");
      out.write("          \t  } else {\r\n");
      out.write("  \t\t    \t  alert(\"취소하였습니다\");\r\n");
      out.write(" \t\t       }\r\n");
      out.write("\t\t    }\r\n");
      out.write("            document.getElementById(\"remod\").onclick = function(){\r\n");
      out.write(" \t\t       location.href=\"replyModify.jsp?lister.get=");
      out.print(listre.get(i).getComment_seq());
      out.write("&one=");
      out.print(num);
      out.write("\";\r\n");
      out.write(" \t\t    }\r\n");
      out.write("          </script>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("         \r\n");
      out.write("\t\t<form\r\n");
      out.write("\t\t\taction=\"reply.jsp?list.get(0).getSeq()=");
      out.print(list.get(0).getSeq());
      out.write("\"\r\n");
      out.write("\t\t\tmethod=\"post\" id=\"re\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\"><input type=\"text\" id=\"replytext\"\r\n");
      out.write("\t\t\t\t\tname=\"comment_text\"></td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" align=\"center\"><button id=\"reply\" type=\"button\">댓글쓰기</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>첨부파일</td>\r\n");
      out.write("\t\t");
  FileDao fdao = new FileDao(); 
		     List<FileInfos> flist = fdao.selectFileData(num);
		     if( flist.size() >0){
		
      out.write("\r\n");
      out.write("\t\t <td colspan=\"4\">\r\n");
      out.write("\t\t      <a href=\"../Download?filename=");
      out.print(flist.get(0).getSystem_file_name());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( flist.get(0).getSystem_file_name() );
      out.write(" </a>\r\n");
      out.write("\t\t </td> \r\n");
      out.write("\t\t ");
}else{ 
      out.write("\r\n");
      out.write("\t\t <td colspan=\"4\">\r\n");
      out.write("\t\t      파일이 없습니다!\r\n");
      out.write("\t\t </td> \r\n");
      out.write("\t\t ");
} 
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">방문 수 :");
      out.print(list.get(0).getSeq());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"3\">작성날짜 ");
      out.print(list.get(0).getWritedate());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t<button id=\"del\" type=\"button\">삭제</button>\r\n");
      out.write("\t\t\t\t<button id=\"upd\" type=\"button\">수정</button>\r\n");
      out.write("\t\t\t\t<button id=\"back\" type=\"button\">뒤로</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\tdocument.getElementById(\"del\").onclick = function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t       var del = confirm(\"삭제하시겠습니까?\") ;\r\n");
      out.write("\t\t       if(del == true){\r\n");
      out.write("\t\t    \t  location.href=\"delete.jsp?list.get(0).getSeq()=");
      out.print(list.get(0).getSeq());
      out.write("\";\r\n");
      out.write("\t\t       } else {\r\n");
      out.write("\t\t    \t  alert(\"취소하였습니다\");\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    document.getElementById(\"back\").onclick = function(){\r\n");
      out.write("\t\t       location.href=\"../BorderList.jsp\";\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    document.getElementById(\"upd\").onclick = function(){\r\n");
      out.write("\t\t\t   location.href=\"update.jsp?list.get(0).getSeq()=");
      out.print(list.get(0).getSeq());
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"reply\").onclick = function() {\r\n");
      out.write("\t\t\tdocument.getElementById(\"re\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

		} else {
	
      out.write("\r\n");
      out.write("\t<table border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th colspan=\"5\" width=\"400\">");
      out.print(list.get(0).getTitle());
      out.write("</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.print(list.get(0).getIp());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.print(list.get(0).getWriter());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"1\">");
      out.print(list.get(0).getViewcount());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr height=\"400\">\r\n");
      out.write("\t\t\t<td colspan=\"5\">");
      out.print(list.get(0).getContents());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");

			ReplyDAO rdao = new ReplyDAO();
				List<ReplyInfo> listre = rdao.showReply(num);

				for (int i = 0; i < listre.size(); i++) {
					if (!(isid.equals(listre.get(i).getWriter()))) {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(listre.get(i).getWriter());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.print(listre.get(i).getComment_text());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(listre.get(i).getIp());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>작성날짜 ");
      out.print(listre.get(i).getWriterdate());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(listre.get(i).getWriter());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"2\">");
      out.print(listre.get(i).getComment_text());
      out.write("</td>\r\n");
      out.write("\t\t\t<td><button id=\"redel\">삭제</button> <button id=\"remod\">수정</button></td>\r\n");
      out.write("\t\t\t<td>작성날짜 ");
      out.print(listre.get(i).getWriterdate());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <script>\r\n");
      out.write("            document.getElementById(\"redel\").onclick = function(){\r\n");
      out.write("            \t var del = confirm(\"삭제하시겠습니까?\")\r\n");
      out.write("            \t  if(del == true){\r\n");
      out.write("            \t\t  location.href=\"deleteReply.jsp?lister.get=");
      out.print(listre.get(i).getComment_seq());
      out.write("&one=");
      out.print(num);
      out.write("\";\r\n");
      out.write("            \t  } else {\r\n");
      out.write("    \t\t    \t  alert(\"취소하였습니다\");\r\n");
      out.write("   \t\t       }\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t    }\r\n");
      out.write("            document.getElementById(\"remod\").onclick = function(){\r\n");
      out.write("            \tlocation.href=\"replyModify.jsp?lister.get=");
      out.print(listre.get(i).getComment_seq());
      out.write("&one=");
      out.print(num);
      out.write("\";\r\n");
      out.write(" \t\t    }\r\n");
      out.write("          </script>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form\r\n");
      out.write("\t\t\taction=\"reply.jsp?list.get(0).getSeq()=");
      out.print(list.get(0).getSeq());
      out.write("\"\r\n");
      out.write("\t\t\tmethod=\"post\" id=\"re2\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\"><input type=\"text\" id=\"replytext\"\r\n");
      out.write("\t\t\t\tname=\"comment_text\"></td>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\"><button id=\"reply\" type=\"button\">댓글쓰기</button></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<tr><td>첨부파일</td>\r\n");
      out.write("\t\t");
  FileDao fdao = new FileDao(); 
		    List<FileInfos> flist = fdao.selectFileData(num);
		    if(flist.size() >0){
		
      out.write("\r\n");
      out.write("\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t      <a href=\"../Download?filename=");
      out.print(flist.get(0).getSystem_file_name());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(flist.get(0).getSystem_file_name() );
      out.write(" </a>\r\n");
      out.write("\t\t </td>\r\n");
      out.write("\t\t ");
}else{ 
      out.write("\r\n");
      out.write("\t\t <td colspan=\"4\">\r\n");
      out.write("\t\t      파일이 없습니다!\r\n");
      out.write("\t\t </td>\r\n");
      out.write("\t\t ");
} 
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">글번호 : ");
      out.print(list.get(0).getSeq());
      out.write("</td>\r\n");
      out.write("\t\t\t<td colspan=\"3\">작성날짜 ");
      out.print(list.get(0).getWritedate());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t<button id=\"back\" type=\"button\">뒤로</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tdocument.getElementById(\"back\").onclick = function() {\r\n");
      out.write("\t\t\tlocation.href = \"../BorderList.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"reply\").onclick = function() {\r\n");
      out.write("\t\t\tlocation.href = \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"reply\").onclick = function() {\r\n");
      out.write("\t\t\tdocument.getElementById(\"re2\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
